importer bug fixes
mediacloud/story-indexer pull request #189
Opened 2023-12-08 14:21 UTC by thepsalmist

Bug Fixes as highlighted in #180

2023-12-08 15:48 UTC, pgulley approved these changes

2023-12-09 01:42 UTC, philbudne requested changes

2023-12-09 01:42 UTC, philbudne commented on indexer/workers/importer.py
> +                # raise exception so that dups are not archived
raising Exceptions (other than QuarantineException) from process_story will cause the story to be retried (a fixed number of times) before the story is thrown to the quarantine queue.  Also, the exception handler in indexer.worker doesn't know about the `raise ... from` construct.  It may (or may not) cause useful information to be put into the queue message headers for later diagnosis.

If the goal is to not pass the story onto the archiver, the correct thing to do is have `process_story` return without calling `sender.send_story`

But, I think what I saw in the graphs in Issue #180 is that duplicates are being counted as "failed", and not showing up in this code path, but rather the one at new line 195 (old line 192) below.

2023-12-09 01:42 UTC, philbudne commented on indexer/workers/importer.py
>                  import_status_label = "failed"
My reading of the graphs in #180 is that duplicate insert attempts are being counted as "failed", so code is needed here to distinguish if that is the case (or whether some other error occurred).

Note: Having this code in a sub-method (import_story) that's called only once makes it harder to "just return from process_story" without throwing an exception or, (gasp) returning status information, so inlining the method might make things simpler.

Finally, if the error is something other than a duplicate, it would be useful to have information in the QuarantineException that helps diagnose what might have caused the error (ie; a repr of the exception or of the response).

2023-12-11 12:47 UTC, thepsalmist commented on indexer/workers/importer.py
>                  import_status_label = "failed"
On the graphs in #180, the PR already provides for three status for failed imports `dups` for duplicates, `reqerr` for 403 errors else `failed`. This should have been displaying on the grafana dashboard, but we hadn't[ updated this](https://github.com/mediacloud/story-indexer/blob/476ea3487c64b9b731a28da45280b1c7b9352a07/conf/grafana/story-indexer-all-realms.json#L419) to a uniform `importer.stories`

2023-12-11 14:10 UTC, kilemensi approved these changes

2023-12-12 18:55 UTC, philbudne commented on indexer/workers/importer.py
>                  import_status_label = "failed"
Note: the current state of affairs is that the The dashboard files in git been downloaded from grafana (where they are currently authored) and checked in to git preserve them:
1. changes may have been made in the dashboards that haven't yet been exported and checked in to git
2. changes made in git will NOT appear in grafana

2023-12-12 19:01 UTC, philbudne commented on indexer/workers/importer.py
>                  import_status_label = "failed"
Manually switching the view to "stories" gives this (does not show successes?):
![image](https://github.com/mediacloud/story-indexer/assets/7842179/af781441-c905-47c7-8b46-5d75d428b144)

2023-12-12 19:04 UTC, philbudne commented on indexer/workers/importer.py
>                  import_status_label = "failed"
A good way to convince me the changes do the right thing is to run a developer instance and capture the (new) grafana output!

2024-01-11 21:58 UTC, philbudne reviewed
Looking directly at the thepsalmist:fix/importer-dup-handling branch (for net effect of PR):

1. It's hard (for me) to tell that each Story will increment exactly one "status" value: what if response is `None` or response.result != "created"?
2. `raise QuarantineException(getattr(e, "message", repr(e)))` discards information on what exception was the cause; see https://github.com/mediacloud/story-indexer/issues/155
3. Catching `Exception` and quarantining means EVERY unhandled error (possibly including ES server unreachable?) is immediately quarantined, instead of retried.  It would be preferable to re-raise (ie; bare `raise`) any unidentified (ie; not KNOWN to be a transient problem) problem, so the Story is retried a number of times before ending up quarantined.

2024-01-16 22:14 UTC, philbudne reviewed
This seems much clearer, but:
1. please don't make changes to the .json files (see the README.md now in main) `The files here have been exported for safe keeping and should not be edited.`
2. in ElasticsearchImporter.import_story: if ElasticsearchConnector.index returns a response object where `response.get("result") != "created"`,a non-None response is returned (story is passed to archiver), and the story is archived, but NOT counted, presumably hasn't been saved in ES, and is neither retried (until finally quarantined), nor immediately quarantined.

2024-01-17 06:26 UTC, philbudne commented
Looking at the ES API docs: https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-index_.html

The only listed values for `result` are `created` and `updated`.

And as a RESTful API, it seems to signal errors via HTTP response codes, which are turned into exceptions by the ES library.

So perhaps the right thing to do is use the `result` value as the status tag to use to increment the counter?  But what to do if no result value is available?  Maybe use `noresult`?

Putting the response check and return inside the `try:` might make it more clear that it only applies
when no exception is raised, and put "return None" (or False, if you return a boolean) at the end???

2024-01-17 14:45 UTC, philbudne approved these changes

2024-01-18 06:58 UTC, merged