Fix/ilm handle duplicates
mediacloud/story-indexer pull request #257
Opened 2024-03-01 12:26 UTC by thepsalmist

2024-03-04 17:12 UTC, kilemensi reviewed
👍🏽 

---

Do we have any data that can tell us the expected performance hit?

2024-03-04 17:12 UTC, kilemensi commented on indexer/workers/importer.py
> +                return None  # mypy explicit return
```suggestion
            response = self.elasticsearch_client().search(
                index=INDEX_NAME_ALIAS,
                body={
                    "query": {
                        "bool": {
                            "filter": {
                                "term": {
                                    "_id": url_hash,
                                    "_tier": "data_warm",
                                }
                            }
                        }
                    },
                    # don't need the actual documents.
                    "size": 0,
                },
            )
            if response["hits"]["total"]["value"] > 0:
                raise ConflictError()
```

After rollover, we only need to search `data_warm` tier. `create` on the client will still check for duplicates in `data_hot` tier.

2024-03-04 17:12 UTC, kilemensi commented on indexer/workers/importer.py
> +            return response
```suggestion
            return url_hash # i.e. response.get("_id")
```

2024-03-04 17:12 UTC, kilemensi commented on indexer/workers/importer.py
> +        # return False
```suggestion
```

2024-03-04 17:12 UTC, kilemensi commented on indexer/tests/test_importer.py
> +        }
```suggestion
        test_extra_data = {
            "normalized_article_title": "the basic principles of would or could",
            "normalized_url": "http://damienafsoe.ttblogs.com/4775282/the-basic-principles-of-would-or-could",
            "text_extraction_method": "trafilatura",
        }
        test_import_data = {
            **test_data,
            **test_extra_data,
            "url": "https://damienafsoe.ttblogs.com/4775282/the-basic-principles-of-would-or-could",
        }
```

We can then use `test_extra_data` in the final asset without having to loop/dictionary comprehension

2024-03-04 17:12 UTC, kilemensi commented on indexer/tests/test_importer.py
> +        id = response.get("_id")
```suggestion
        id = importer.import_story(test_import_data)
        assert id
```

2024-03-04 17:12 UTC, kilemensi commented on indexer/tests/test_importer.py
> +        for key in additional_keys:
```suggestion
        for key in test_extra_data:
```

2024-03-04 17:12 UTC, kilemensi commented on indexer/tests/test_importer.py
> +        assert search_response["hits"]["total"]["value"] == 0, "Document already exists"
If I'm reading the test correctly, the document should **NOT** exist at this point.

2024-03-04 17:20 UTC, philbudne commented on indexer/workers/importer.py
> +    ) -> ObjectApiResponse | None:
I agree: avoid returning complex types from a library when a simple/useful one will do.

On the point of whether to start using `|` in place of Union in new code: This seems like a slippery slope, and that it will require immense willpower to avoid making changes in nearby lines.  There's also the question of whether to use `X | None` in place of `Optional[X]`.

Frankly, I find it more disturbing to see a mixture of conventions than to stick with an old one.

Python is constantly mutating, and this won't be the last time a question like this comes up!!!

2024-03-04 17:27 UTC, philbudne commented on indexer/workers/importer.py
> +    ) -> ObjectApiResponse | None:
I'm reposting the above to slack, a better place for discussion!

2024-03-05 07:07 UTC, thepsalmist commented on indexer/workers/importer.py
> +                return None  # mypy explicit return
@kilemensi searching by data tier makes sense, however we concluded to have all three hot nodes(ramos,bradley,woodward) based on [this discussions](https://github.com/mediacloud/story-indexer/issues/205)

2024-03-05 09:43 UTC, thepsalmist commented on indexer/workers/importer.py
> +    ) -> ObjectApiResponse | None:
Based on

> I think standardizing on a runtime version is great (3.10?), and recognize that can be different from decisions about code conventions and consistency (which could be pegged to 3.9 style).

2024-03-05 10:17 UTC, kilemensi commented on indexer/workers/importer.py
> +                return None  # mypy explicit return
Cool @thepsalmist. If this was agreed, the the backup/snapshot plan also needs to be updated. Otherwise stories such as #253 and #254 still refer to ideas of cold/warm tiers.

2024-03-05 12:10 UTC, thepsalmist commented on indexer/workers/importer.py
> +                return None  # mypy explicit return
Updated #253 @kilemensi

2024-03-05 12:12 UTC, thepsalmist commented on indexer/workers/importer.py
> +                return None  # mypy explicit return
>  # don't need the actual documents.

We dont need to return the actual documents,'optimizing' our search query. Query checks for existence

2024-03-05 16:23 UTC, philbudne requested changes

2024-03-05 16:23 UTC, philbudne commented on indexer/workers/importer.py
> +    ) -> str | None:
1. The return value is still only used (in importer.py) as a bool, does the return type need to change?
2. if it does, update the docstring below!!!
3. My preference is to stick with Optional.. It hurts my brain to see Optional one line above (the slippery slope)

2024-03-05 16:23 UTC, philbudne commented on indexer/workers/importer.py
> +                self.incr_stories("dups", url)
I'd rather have a different counter name (dups2?), since it's a different condition.

2024-03-06 06:45 UTC, thepsalmist commented on indexer/workers/importer.py
> +                self.incr_stories("dups", url)
Cool, I recall there was a limit to how many characters the counter name would be, could gi wuth `ilm-dups` for more clarity

2024-03-06 06:53 UTC, thepsalmist commented on indexer/workers/importer.py
> +    ) -> str | None:
1. We're returning the str(url_hash) for tests that involve search hence Optional[str]

2024-03-06 13:54 UTC, kilemensi approved these changes
LGTM!

2024-03-06 14:36 UTC, philbudne approved these changes

2024-03-06 15:50 UTC, pgulley approved these changes

2024-03-06 16:17 UTC, merged