Hotfix/csv queuer fetcher
mediacloud/story-indexer pull request #288
Opened 2024-05-15 07:02 UTC by thepsalmist

2024-05-15 19:21 UTC, philbudne commented
Some preliminary comments:
1. The branch seems to contain other stuff (`HIST_YEAR=2023` and `add ELASTICSEARCH_SNAPSHOT_REPO`)?  It's best practice to have PRs based on main.
2. I think the pipeline type "csv-fetcher" is misleading; I suggest using "csv": It runs a different queuer that feeds into the (regular) queue-based fetcher and I think it's likely to be (re)used in the future, as opposed to being used only once.
3. In csv-queuer:
  * I don't think any of the commented out code in csv-queuer.py needs to be kept around. 
  * the comment `# let hist-fetcher quarantine if bad` should go away
  * the large block comment on `urls_seen` is no longer meaningful (since the CSV file is unlikely to have come from the legacy system), BUT filtering for duplicate urls is probably still a good idea (doesn't cost much, and can save time/effort).
 * the comment block `# content_metadata.parsed_date is not set, so parser.py will` can go away 
 *  `rss.source_feed_id = None` and `rss.source_source_id = None` can go away (should be the default value)
  * `rss.source_url = url` can go away: we don't have the URL of the RSS file the story was found in.
4. in deploy.sh:
 * `PIPE_TYPE_PFX='hist-'` I suggest use `csv-` and setting `PORT_BIAS=600` to allow co-existence with other stacks
 * Would be good to set "ARCH_SUFFIX=csv" so the generated WARC files are distinct from the current day ones

2024-05-17 16:05 UTC, kilemensi commented on indexer/workers/fetcher/csv-queuer.py
> +                continue
Aside (not for this PR): Seems like `self.check_story_url` does most of the check that this if does and we _probably_ don't need both (similarly in `hist-queue.py`)

2024-05-17 16:14 UTC, thepsalmist commented on docker/docker-compose.yml.j2
> +{% elif pipeline_type == 'queue-fetcher' or pipeline_type == 'csv' %}
We still want to spin the `queue-fetcher`, to do the fetching although being fed from a `csv-queuer` not the typical `rss-queuer`

2024-05-17 16:21 UTC, thepsalmist commented on indexer/workers/fetcher/csv-queuer.py
> +                rss.source_url = url
> Do we know this?

Could you clarify on this?

2024-05-17 16:33 UTC, thepsalmist commented on indexer/workers/fetcher/csv-queuer.py
> +            with story.rss_entry() as rss:
Sure

2024-05-17 16:47 UTC, thepsalmist commented on indexer/workers/fetcher/csv-queuer.py
> +                continue
Yes, `self.check_story_url` does most of the validation, one edge case not handled when url = "".

2024-05-17 17:14 UTC, philbudne requested changes

2024-05-17 17:14 UTC, philbudne commented on indexer/workers/fetcher/csv-queuer.py
> +        "Read CSV of historical stories, queue to hist-fetcher",
"queue to regular fetcher"

2024-05-17 17:25 UTC, kilemensi commented on indexer/workers/fetcher/csv-queuer.py
> +                rss.source_url = url
Sorry... Been a while but _if I remember correctly_, `rss.source_url` the URL of the RSS file itself. Hence, do we know if `url` is `rss.source_url`?

2024-05-17 17:35 UTC, kilemensi commented on indexer/workers/fetcher/csv-queuer.py
> +                continue
[`if not url:`](https://github.com/mediacloud/story-indexer/blob/3b10677cf4c2e7ef24306e1a5c4993418821f06c/indexer/storyapp.py#L122) should handle when `url` is `""`.

2024-05-20 15:59 UTC, philbudne approved these changes

2024-05-21 06:47 UTC, merged